# Generated by Django 4.0.5 on 2023-08-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_audiorecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publishing_date', models.CharField(max_length=200)),
                ('page_number', models.CharField(max_length=200)),
                ('ratings', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=1000)),
            ],
        ),
    ]
