# Generated by Django 4.0.5 on 2023-08-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishing_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='name_of_book',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
